### Høyt sykefravær bidrar til flere som mottar AAP {.unnumbered}


::: {.callout icon=false}
Publisert 15. april 2024 | Oppdatert 15. april 2024
:::

Ved utgangen av første kvartal mottok 152 598 personer arbeidsavklaringspenger. Dette er nesten 9000 flere enn på samme tid i 2023.

Det betyr at 4,2 prosent av befolkningen i aldersgruppa 18-66 år nå mottar arbeidsavklaringspenger.

– Det er fortsatt mange som starter på ytelsen, samtidig som antall som slutter holdt seg lavt gjennom hele fjoråret. Utviklingen må ses i sammenheng med fjerningen av karensbestemmelsen. I tillegg har vi et høyt sykefravær og det bidrar også til at flere går over fra sykepenger til arbeidsavklaringspenger, sier arbeids- og velferdsdirektør Hans Christian Holte.

```{python}
#| include: false
# include: false skjuler warning fra BQ
from hjelpefunksjoner import pressemelding_plott
max_aarmnd = 202406
fig = pressemelding_plott(max_aarmnd = max_aarmnd)
```

```{python}
#| echo: false
fig.show()
```

*Kilde: Nav*

*Data til plott på andel er ikke i BigQuery*


#### Antallet som starter er stabilt høyt
I første kvartal 2024 var det 17 600 personer som startet å motta AAP. Antallet som starter på AAP har holdt seg høyt siden begynnelsen på koronapandemien. Sammenlikner vi tilgangen i første kvartal med tilsvarende periode i 2019, er det fortsatt rundt 2 000 flere som starter på i ytelsen i dag.

Det tyder på at det fortsatt er et høyt sykdomstrykk, men henger også sammen med vedvarende høyt sykefravær som bidrar til at flere har overgang til AAP etter å ha brukt opp sykepengeretten.

#### Reduksjon i antall som slutter på ytelsen
Det var til sammen 12 600 personer som sluttet å motta AAP i fjerde kvartal 2023. Sammenliknet med året før var det rundt 2 000 færre som gikk ut av ytelsen. Nedgangen må allikevel ses i sammenheng med at forlengelsene under koronapandemien, og de midlertidige forlengelsene i forbindelse med regelverksendringene i 2022. Dette førte til at svært mange nådde maksperiode ved utgangen av oktober 2022. Selv om mange fikk fortsette som følge av det nye regelverket fra samme år, var det allikevel en del som ble avklart og forsvant ut av AA- ytelsen.

Samtidig ser vi at antallet som slutter på AAP fortsetter å holde seg lavt sammenliknet med perioden før koronapandemien og regelverksendringene. Det var eksempelvis 2 600 færre som sluttet å motta i fjerde kvartal, sammenliknet med tilsvarende periode i 2019.

#### Kraftig økning i bruk av lønnstilskudd
I mars var det 63 900 personer med nedsatt arbeidsevne som deltok i arbeidsmarkedstiltak. Dette er en økning på 7 prosent fra fjoråret. Rundt 9 200 var registrert med arbeidsmarkedstiltaket lønnstilskudd. Antallet er økt med rundt 1 600, fra tilsvarende periode i 2023. En stor andel av denne økningen skyldes at det var over 500 flere ukrainere som deltok i tiltaket.

#### Lavere sannsynlighet for å slutte 
Sannsynligheten for å fortsatt motta AAP økte med 1,6 prosentpoeng fra fjoråret, og vi ser at det har ført til en redusert sannsynlighet for å motta uføretrygd, men også for å være i arbeid. Dette gjenspeiles ved at det sammenliknet med året før var rundt 2 prosentpoeng færre som var i arbeid mot slutten av 2023, etter at de hadde avgang 6 måneder tidligere.

–  En økt sannsynlighet for å fortsette på ytelsen må ses i sammenheng med regelverksendringene fra 2022, men det er samtidig sannsynlig at et noe dårligere arbeidsmarked isolert kan føre til lavere avgang til arbeid, sier Holte.


::: {.callout-tip }

#### Fakta
**Forlengelse av perioden med arbeidsavklaringspenger (AAP)**

Fra og med 1. juli 2022 er det også gjort endringer i «karensbestemmelsen». Endringene innebærer en oppheving av bestemmelsen som har medført at personer i de fleste tilfeller må ha ventet 52 uker før det er mulig å søke arbeidsavklaringspenger på nytt dersom de har gått ut maksimal stønadsperiode.

:::